### ISSUE TITLE
Why the coin type of BitShares is not in bip44 constants ? 

### ISSUE THREAD

**Issue by BIIYANG** [bitcoinjs/bip44-constants#14]
Hi,
     Why the coin type of BitShares is not in bip44 constants ?   https://bitshares.org/    
If it's not in , How can I do to add it  ?  We are developing a HD Wallet need to support BitShares. 
Thanks.

**Comment by fanatid** [comment]
Constants are fetched from https://github.com/satoshilabs/slips/blob/master/slip-0044.md
Sometimes we update package with new constants. (We have all this info in README.md)
