### ISSUE TITLE
Coins with same symbols

### ISSUE THREAD

**Issue by kolya182** [bitcoinjs/bip44-constants#29]
Accordingly to https://github.com/satoshilabs/slips/blob/master/slip-0044.md  there are two coins with same `LBTC` symbol but different `coind`. In such a case we have just one `LBTC`https://github.com/bitcoinjs/bip44-constants/blob/6e9d208a825cffbb5603dbd059fa1179d7a9170c/index.js#L196 How we should handle duplicate symbols ?.

**Comment by junderw** [comment]
@kolya182 Thoughts on #30 ?

**Comment by junderw** [comment]
Fixed in #31
