### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bip44-constants#4]
https://github.com/bitcoinjs/bip44-constants/pull/3#issuecomment-275030540

**Comment by fanatid** [comment]
I already fixed travis, build will not be run if `.travis.yml` is not presented.
https://travis-ci.org/bitcoinjs/bip44-constants/settings

**Comment by dcousens** [comment]
I guess https://travis-ci.org/bitcoinjs/bip44-constants/builds/194804298 was before you enabled that then?

**Comment by fanatid** [comment]
yep, I had seen that travis failed and I changed settings
