### ISSUE TITLE
Auto-publisher

### ISSUE THREAD

**Issue by junderw** [bitcoinjs/bip44-constants#42]
I will consider adding an AWS cloudformation template that will run a Lambda job once every week or so to bump the patch version with the latest SLIP-44 constants...

If anyone wants to do it for me I'd appreciate it.

**Comment by kolya182** [comment]
Maybe consider github actions to be less dependent on AWS ?.

**Comment by junderw** [comment]
good point.

Are you well versed in Github Actions?

1. Every day run update.
2. If no changes exit.
3. If changes, commit, bump version, push to github, publish to npm.

If we can do that they awesome.

Since we already trust Github heavily, it shouldn't be too much of a security risk to allow Github to host it.

**Comment by junderw** [comment]
Events can be scheduled... nice.

https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule

I'll look into it later this week.

**Comment by junderw** [comment]
Added in https://github.com/bitcoinjs/bip44-constants/commit/df6ed27b1c296b602fe1009c6ecdfa125c252452

Had to create a new npm account just for this, and added a deploy key to this repo on github, but 8.0.7 had already been published, and the update is committed and tagged on github.

Closing.

**Comment by junderw** [comment]
set the job to run once a day @ 2:42 am UTC

https://github.com/bitcoinjs/bip44-constants/commit/cd8d0c83ce12417b39b29ad06de7977c2d0b3d2e
