### ISSUE TITLE
update.js is not working anymore

### ISSUE THREAD

**Issue by AntonioVentilii** [bitcoinjs/bip44-constants#59]
Script `update.js` is returning an empty list. Version `307.0.0` was published with an empty list.

**Comment by AntonioVentilii** [comment]
Created PR #61 to solve this

**Comment by junderw** [comment]
Thanks!

**Comment by junderw** [comment]
A new version will go out in about 10 hours.

**Comment by junderw** [comment]
I deprecated the most recent version

**Comment by AntonioVentilii-DFINITY** [comment]
Thank you!
