### ISSUE TITLE
Why are we exporting string constants?

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bip44-constants#9]
We even recommend `parseInt` in the README...

**Comment by dcousens** [comment]
BIP32 cannot support >32-bit derivation indexes??

**Comment by fanatid** [comment]
I believe original reason why @jprichardson did this was that string constants easy for review and compare with `slip-0044`

**Comment by jprichardson** [comment]
Yep, that's exactly right. I don't have any strong feelings on this and don't care if we change it.

**Comment by dcousens** [comment]
See https://github.com/bitcoinjs/bip44-constants/pull/10
